import type {
  ActivityItem,
  AiAsset,
  Certificate,
  Domain,
  Mailbox,
  Secret,
  Server,
  Snapshot,
} from "./types";

export const SEED_SERVERS: Server[] = [
  {
    id: "srv_tokyo",
    name: "tokyo-prod-01",
    label: "东京生产",
    host: "47.74.18.102",
    port: 22,
    username: "root",
    os: "Ubuntu 24.04 LTS",
    region: "ap-northeast-1 · 东京",
    tags: ["prod", "web", "nginx"],
    status: "online",
    cpu: 18,
    memory: 41,
    disk: 36,
    uptime: "47 天",
    lastSeen: new Date(Date.now() - 42_000).toISOString(),
    notes: "主站与 API 网关。Cloudflare 回源，夜间 02:00 备份到 hz-backup。",
  },
  {
    id: "srv_hk",
    name: "hk-edge-02",
    label: "香港边缘",
    host: "43.129.55.71",
    port: 22,
    username: "deploy",
    os: "Debian 12",
    region: "ap-east-1 · 香港",
    tags: ["edge", "cdn"],
    status: "warning",
    cpu: 86,
    memory: 72,
    disk: 54,
    uptime: "12 天",
    lastSeen: new Date(Date.now() - 8_000).toISOString(),
    notes: "边缘节点，CPU 持续偏高。计划本周扩容 2C。",
  },
  {
    id: "srv_sg",
    name: "sg-db-primary",
    label: "新加坡主库",
    host: "8.222.41.19",
    port: 22,
    username: "ops",
    os: "Ubuntu 22.04 LTS",
    region: "ap-southeast-1 · 新加坡",
    tags: ["prod", "postgres"],
    status: "online",
    cpu: 33,
    memory: 61,
    disk: 48,
    uptime: "103 天",
    lastSeen: new Date(Date.now() - 15_000).toISOString(),
    notes: "PostgreSQL 16 主库，流复制到杭州。勿在高峰窗口重启。",
  },
  {
    id: "srv_usw",
    name: "usw-dev-04",
    label: "美西开发",
    host: "54.183.90.44",
    port: 22,
    username: "ubuntu",
    os: "Amazon Linux 2023",
    region: "us-west-1 · 俄勒冈",
    tags: ["dev"],
    status: "offline",
    cpu: 0,
    memory: 0,
    disk: 22,
    uptime: "—",
    lastSeen: new Date(Date.now() - 36 * 3600_000).toISOString(),
    notes: "开发机，已关机以节省账单。需要时从控制台开机。",
  },
  {
    id: "srv_hz",
    name: "hz-backup",
    label: "杭州备份",
    host: "120.55.210.88",
    port: 22,
    username: "backup",
    os: "Rocky Linux 9",
    region: "cn-hangzhou · 杭州",
    tags: ["backup", "cold"],
    status: "online",
    cpu: 7,
    memory: 28,
    disk: 71,
    uptime: "210 天",
    lastSeen: new Date(Date.now() - 120_000).toISOString(),
    notes: "冷备与对象存储网关。磁盘占用已过 70%，下月扩容。",
  },
];

export const SEED_DOMAINS: Domain[] = [
  {
    id: "dom_studio",
    tags: ["主站", "生产"],
    name: "studio.nexus.app",
    registrar: "Cloudflare",
    expiresAt: "2027-04-12",
    dns: "Cloudflare",
    nameservers: ["ada.ns.cloudflare.com", "bob.ns.cloudflare.com"],
    autoRenew: true,
    status: "online",
    notes: "主站与控制台。DNSSEC 已开。",
  },
  {
    id: "dom_mail",
    tags: ["邮件"],
    name: "suu.dev",
    registrar: "Namecheap",
    expiresAt: isoInDays(18),
    dns: "Cloudflare",
    nameservers: ["ada.ns.cloudflare.com", "bob.ns.cloudflare.com"],
    autoRenew: false,
    status: "warning",
    notes: "个人域名，自动续费未开。18 天内到期。",
  },
  {
    id: "dom_api",
    tags: ["API", "生产"],
    name: "harbor.io",
    registrar: "Porkbun",
    expiresAt: "2026-12-02",
    dns: "Porkbun",
    nameservers: ["curitiba.ns.porkbun.com", "fortaleza.ns.porkbun.com"],
    autoRenew: true,
    status: "online",
    notes: "API 与文档站。",
  },
  {
    id: "dom_vault",
    tags: ["个人"],
    name: "vault.me",
    registrar: "Cloudflare",
    expiresAt: isoInDays(4),
    dns: "Cloudflare",
    nameservers: ["ada.ns.cloudflare.com", "bob.ns.cloudflare.com"],
    autoRenew: false,
    status: "offline",
    notes: "即将到期，且未开自动续费。",
  },
];

export const SEED_MAIL: Mailbox[] = [
  {
    id: "mail_hello",
    tags: ["主站", "对外"],
    address: "hello@studio.nexus.app",
    domain: "studio.nexus.app",
    kind: "mailbox",
    usedMb: 1240,
    quotaMb: 10240,
    status: "online",
    notes: "对外联系主箱。",
  },
  {
    id: "mail_bill",
    tags: ["主站", "财务"],
    address: "billing@studio.nexus.app",
    domain: "studio.nexus.app",
    kind: "mailbox",
    usedMb: 420,
    quotaMb: 5120,
    status: "online",
    notes: "收据与发票。",
  },
  {
    id: "mail_alias",
    tags: ["邮件", "对外"],
    address: "hi@suu.dev",
    domain: "suu.dev",
    kind: "alias",
    usedMb: 0,
    quotaMb: 0,
    forwardTo: "hello@studio.nexus.app",
    status: "online",
    notes: "个人短别名。",
  },
  {
    id: "mail_post",
    tags: ["邮件"],
    address: "postmaster@suu.dev",
    domain: "suu.dev",
    kind: "forward",
    usedMb: 86,
    quotaMb: 512,
    forwardTo: "hello@studio.nexus.app",
    status: "warning",
    notes: "配额将满，建议清理退信。",
  },
];

export const SEED_AI: AiAsset[] = [
  {
    id: "ai_gpt_plus",
    tags: ["订阅", "个人"],
    name: "ChatGPT Plus",
    provider: "OpenAI",
    plan: "Plus / 月付",
    keyHint: "•••• 不涉及密钥",
    monthlyUsd: 20,
    usagePct: 64,
    renewsAt: isoInDays(11),
    status: "online",
    notes: "日常对话与写作。",
  },
  {
    id: "ai_claude",
    tags: ["订阅", "个人"],
    name: "Claude Pro",
    provider: "Anthropic",
    plan: "Pro / 月付",
    keyHint: "•••• 不涉及密钥",
    monthlyUsd: 20,
    usagePct: 41,
    renewsAt: isoInDays(19),
    status: "online",
    notes: "长文与代码审阅。",
  },
  {
    id: "ai_grok",
    tags: ["订阅", "个人"],
    name: "Grok Super",
    provider: "xAI",
    plan: "SuperGrok",
    keyHint: "•••• 不涉及密钥",
    monthlyUsd: 30,
    usagePct: 55,
    renewsAt: isoInDays(6),
    status: "online",
    notes: "搜索与实时信息。",
  },
  {
    id: "ai_oai_api",
    tags: ["API", "按量"],
    name: "OpenAI API",
    provider: "OpenAI",
    plan: "Pay as you go",
    keyHint: "sk-…7f2a",
    monthlyUsd: 86,
    usagePct: 91,
    renewsAt: isoInDays(26),
    status: "warning",
    notes: "本月用量接近软上限 $100。",
  },
  {
    id: "ai_anth_api",
    tags: ["API", "按量"],
    name: "Anthropic API",
    provider: "Anthropic",
    plan: "Pay as you go",
    keyHint: "sk-ant-…c91e",
    monthlyUsd: 42,
    usagePct: 37,
    renewsAt: isoInDays(26),
    status: "online",
    notes: "Claude 3.7 生产调用。",
  },
];

export const SEED_SECRETS: Secret[] = [
  {
    id: "sec_gh",
    tags: ["开发"],
    name: "GitHub PAT",
    kind: "token",
    hint: "ghp_…8c21",
    value: "ghp_demo_not_a_real_token_8c21",
    lastRotated: isoInDays(-40),
    status: "online",
    notes: "repo + workflow 权限。",
  },
  {
    id: "sec_cf",
    tags: ["基础设施"],
    name: "Cloudflare API",
    kind: "api",
    hint: "cf-…b3e0",
    value: "cf_demo_token_b3e0",
    lastRotated: isoInDays(-12),
    status: "online",
    notes: "Zone DNS 编辑。",
  },
  {
    id: "sec_aws",
    tags: ["基础设施"],
    name: "AWS Access Key",
    kind: "api",
    hint: "AKIA…9K2P",
    value: "AKIADEMO9K2P",
    lastRotated: isoInDays(-210),
    status: "warning",
    notes: "超过 180 天未轮换。",
  },
  {
    id: "sec_ssh",
    tags: ["基础设施", "生产"],
    name: "tokyo-prod-01 私钥",
    kind: "ssh",
    hint: "ed25519 · 指纹 a8:f3",
    value: "-----BEGIN OPENSSH PRIVATE KEY-----\ndemo\n-----END OPENSSH PRIVATE KEY-----",
    lastRotated: isoInDays(-90),
    status: "online",
    notes: "仅本机使用，已加 passphrase。",
  },
  {
    id: "sec_stripe",
    tags: ["财务"],
    name: "Stripe Live",
    kind: "api",
    hint: "sk_live_…d44",
    value: "sk_live_demo_d44",
    lastRotated: isoInDays(-70),
    status: "online",
    notes: "收款。",
  },
];

export const SEED_CERTS: Certificate[] = [
  {
    id: "crt_studio",
    tags: ["主站", "生产"],
    cn: "studio.nexus.app",
    issuer: "Let's Encrypt R12",
    expiresAt: isoInDays(62),
    sans: ["studio.nexus.app", "www.studio.nexus.app"],
    status: "online",
    notes: "自动续签 via certbot。",
  },
  {
    id: "crt_mail",
    tags: ["邮件"],
    cn: "mail.suu.dev",
    issuer: "Let's Encrypt R12",
    expiresAt: isoInDays(12),
    sans: ["mail.suu.dev"],
    status: "warning",
    notes: "12 天后到期，检查续签任务。",
  },
  {
    id: "crt_wild",
    tags: ["API", "生产"],
    cn: "*.harbor.io",
    issuer: "Google Trust Services",
    expiresAt: isoInDays(3),
    sans: ["*.harbor.io", "harbor.io"],
    status: "offline",
    notes: "通配符证书即将过期。",
  },
];

export const SEED_ACTIVITY: ActivityItem[] = [
  {
    id: "act_1",
    at: new Date(Date.now() - 8 * 60_000).toISOString(),
    text: "hk-edge-02 CPU 连续 10 分钟高于 80%",
    kind: "server",
  },
  {
    id: "act_2",
    at: new Date(Date.now() - 2 * 3600_000).toISOString(),
    text: "证书 *.harbor.io 进入 3 天倒计时",
    kind: "cert",
  },
  {
    id: "act_3",
    at: new Date(Date.now() - 5 * 3600_000).toISOString(),
    text: "OpenAI API 本月用量越过 90%",
    kind: "ai",
  },
  {
    id: "act_4",
    at: new Date(Date.now() - 26 * 3600_000).toISOString(),
    text: "usw-dev-04 已关机",
    kind: "server",
  },
  {
    id: "act_5",
    at: new Date(Date.now() - 48 * 3600_000).toISOString(),
    text: "tokyo-prod-01 夜间备份完成 · 2.4 GB",
    kind: "server",
  },
];

export const SEED_SNAPSHOT: Snapshot = {
  servers: SEED_SERVERS,
  domains: SEED_DOMAINS,
  mailboxes: SEED_MAIL,
  aiAssets: SEED_AI,
  secrets: SEED_SECRETS,
  certs: SEED_CERTS,
};

/**
 * The desktop app starts here.
 *
 * Sample hosts would be actively misleading once the buttons really dial out:
 * every card would be a connection failure to somebody else's IP address. The
 * web preview keeps the seed, because there it is a demo and nothing else.
 */
export const EMPTY_SNAPSHOT: Snapshot = {
  servers: [],
  domains: [],
  mailboxes: [],
  aiAssets: [],
  secrets: [],
  certs: [],
};

function isoInDays(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}
